<?php

use App\Http\Controllers\ArtworkThumbnailController;
use App\Http\Controllers\AudioStreamController;
use App\Http\Controllers\CatalogBrowseController;
use App\Http\Controllers\DashboardMetricsController;
use App\Http\Controllers\FavoritesController;
use App\Http\Controllers\FolderBrowserController;
use App\Http\Controllers\PlaylistsController;
use App\Http\Controllers\TrackPlayStatisticsController;
use Illuminate\Support\Facades\Route;

Route::get('/catalog/artists', [CatalogBrowseController::class, 'artists']);
Route::get('/catalog/albums', [CatalogBrowseController::class, 'albums']);
Route::get('/catalog/playback/albums/random', [CatalogBrowseController::class, 'randomAlbum']);
Route::get('/catalog/playback/albums/{album}/next', [CatalogBrowseController::class, 'nextAlbum']);
Route::get('/catalog/playback/tracks/random', [CatalogBrowseController::class, 'randomTrack']);
Route::get('/catalog/playback/tracks/{track}/next', [CatalogBrowseController::class, 'nextTrack']);
Route::get('/catalog/albums/{album}', [CatalogBrowseController::class, 'album']);
Route::get('/catalog/tracks', [CatalogBrowseController::class, 'tracks']);
Route::get('/catalog/tracks/{track}', [CatalogBrowseController::class, 'track']);
Route::get('/catalog/genres', [CatalogBrowseController::class, 'genres']);
Route::get('/artwork/{artwork}/thumbnail', ArtworkThumbnailController::class);
Route::get('/artwork/{artwork}/original', [ArtworkThumbnailController::class, 'original']);
Route::get('/tracks/{track}/stream', AudioStreamController::class);
Route::post('/tracks/{track}/plays', [TrackPlayStatisticsController::class, 'store']);
Route::get('/dashboard-metrics', DashboardMetricsController::class);
Route::get('/folders', FolderBrowserController::class);
Route::get('/favorites', [FavoritesController::class, 'ids']);
Route::get('/favorites/tracks', [FavoritesController::class, 'tracks']);
Route::post('/favorites/tracks/{track}', [FavoritesController::class, 'addTrack']);
Route::delete('/favorites/tracks/{track}', [FavoritesController::class, 'removeTrack']);
Route::get('/favorites/albums', [FavoritesController::class, 'albums']);
Route::post('/favorites/albums/{album}', [FavoritesController::class, 'addAlbum']);
Route::delete('/favorites/albums/{album}', [FavoritesController::class, 'removeAlbum']);
Route::get('/playlist-folders', [PlaylistsController::class, 'folders']);
Route::post('/playlist-folders', [PlaylistsController::class, 'createFolder']);
Route::patch('/playlist-folders/{folder}', [PlaylistsController::class, 'updateFolder']);
Route::delete('/playlist-folders/{folder}', [PlaylistsController::class, 'deleteFolder']);
Route::get('/playlists', [PlaylistsController::class, 'playlists']);
Route::post('/playlists', [PlaylistsController::class, 'createPlaylist']);
Route::get('/playlists/{playlist}', [PlaylistsController::class, 'playlist']);
Route::patch('/playlists/{playlist}', [PlaylistsController::class, 'updatePlaylist']);
Route::delete('/playlists/{playlist}', [PlaylistsController::class, 'deletePlaylist']);
Route::post('/playlists/{playlist}/tracks', [PlaylistsController::class, 'addTracks']);
Route::post('/playlists/{playlist}/tracks/{track}', [PlaylistsController::class, 'addTrack']);
Route::delete('/playlists/{playlist}/items', [PlaylistsController::class, 'removeItems']);
Route::delete('/playlists/{playlist}/items/{item}', [PlaylistsController::class, 'removeItem']);
Route::patch('/playlists/{playlist}/items/reorder', [PlaylistsController::class, 'reorderItems']);
