<?php

use App\Http\Controllers\AdminAccessController;
use App\Http\Controllers\AlbumMetadataController;
use App\Http\Controllers\AlbumTrackMetadataController;
use App\Http\Controllers\ArtworkThumbnailController;
use App\Http\Controllers\AudioStreamController;
use App\Http\Controllers\CatalogBrowseController;
use App\Http\Controllers\DashboardMetricsController;
use App\Http\Controllers\FavoritesController;
use App\Http\Controllers\FolderBrowserController;
use App\Http\Controllers\LastFmSettingsController;
use App\Http\Controllers\MetadataBackupSettingsController;
use App\Http\Controllers\OnlineEnrichmentSettingsController;
use App\Http\Controllers\OnlineEnrichmentController;
use App\Http\Controllers\PlaybackStatisticsController;
use App\Http\Controllers\PlaybackStatisticsSettingsController;
use App\Http\Controllers\PlaylistsController;
use App\Http\Controllers\TrackMetadataController;
use App\Http\Controllers\TrackPlayStatisticsController;
use Illuminate\Support\Facades\Route;

Route::get('/catalog/artists', [CatalogBrowseController::class, 'artists']);
Route::get('/catalog/artists/{artist}', [CatalogBrowseController::class, 'artist']);
Route::get('/catalog/albums', [CatalogBrowseController::class, 'albums']);
Route::get('/catalog/playback/albums/random', [CatalogBrowseController::class, 'randomAlbum']);
Route::get('/catalog/playback/albums/{album}/next', [CatalogBrowseController::class, 'nextAlbum']);
Route::get('/catalog/playback/tracks/random', [CatalogBrowseController::class, 'randomTrack']);
Route::get('/catalog/playback/tracks/{track}/next', [CatalogBrowseController::class, 'nextTrack']);
Route::get('/catalog/albums/{album}', [CatalogBrowseController::class, 'album']);
Route::get('/albums/{album}/artwork/original', [ArtworkThumbnailController::class, 'albumOriginal']);
Route::post('/albums/{album}/metadata/preview', [AlbumMetadataController::class, 'preview']);
Route::post('/albums/{album}/metadata-edits', [AlbumMetadataController::class, 'store']);
Route::post('/albums/{album}/tracks/metadata/preview', [AlbumTrackMetadataController::class, 'preview']);
Route::post('/albums/{album}/tracks/metadata-edits', [AlbumTrackMetadataController::class, 'store']);
Route::get('/catalog/tracks', [CatalogBrowseController::class, 'tracks']);
Route::get('/catalog/tracks/{track}', [CatalogBrowseController::class, 'track']);
Route::get('/catalog/genres', [CatalogBrowseController::class, 'genres']);
Route::get('/artwork/{artwork}/thumbnail', ArtworkThumbnailController::class);
Route::get('/tracks/{track}/stream', AudioStreamController::class);
Route::post('/tracks/{track}/plays', [TrackPlayStatisticsController::class, 'store']);
Route::post('/tracks/{track}/metadata/preview', [TrackMetadataController::class, 'preview']);
Route::post('/tracks/{track}/metadata-edits', [TrackMetadataController::class, 'store']);
Route::get('/metadata-edits/{metadataEditJob}', [TrackMetadataController::class, 'show']);
Route::get('/statistics/recent-plays', [PlaybackStatisticsController::class, 'recentPlays']);
Route::get('/statistics/most-played-tracks', [PlaybackStatisticsController::class, 'mostPlayedTracks']);
Route::get('/statistics/most-played-albums', [PlaybackStatisticsController::class, 'mostPlayedAlbums']);
Route::get('/statistics/tracks/{track}/recent-plays', [PlaybackStatisticsController::class, 'trackRecentPlays']);
Route::get('/settings/playback-statistics', [PlaybackStatisticsSettingsController::class, 'show']);
Route::get('/settings/access', AdminAccessController::class);
Route::patch('/settings/playback-statistics', [PlaybackStatisticsSettingsController::class, 'update']);
Route::get('/settings/metadata-backups', [MetadataBackupSettingsController::class, 'show']);
Route::patch('/settings/metadata-backups', [MetadataBackupSettingsController::class, 'update']);
Route::get('/settings/lastfm', [LastFmSettingsController::class, 'show']);
Route::post('/settings/lastfm/connect', [LastFmSettingsController::class, 'connect']);
Route::post('/settings/lastfm/complete', [LastFmSettingsController::class, 'complete']);
Route::patch('/settings/lastfm', [LastFmSettingsController::class, 'update']);
Route::delete('/settings/lastfm', [LastFmSettingsController::class, 'disconnect']);
Route::get('/settings/online-enrichment', [OnlineEnrichmentSettingsController::class, 'show']);
Route::patch('/settings/online-enrichment', [OnlineEnrichmentSettingsController::class, 'update']);
Route::delete('/settings/online-enrichment/cache', [OnlineEnrichmentSettingsController::class, 'clearCache']);
Route::post('/settings/online-enrichment/providers/{provider}/test', [OnlineEnrichmentSettingsController::class, 'testProvider']);
Route::get('/enrichment/tracks/{track}/information', [OnlineEnrichmentController::class, 'information']);
Route::get('/enrichment/tracks/{track}/identity', [OnlineEnrichmentController::class, 'identity']);
Route::get('/enrichment/tracks/{track}/artist-image', [OnlineEnrichmentController::class, 'artistImage']);
Route::get('/enrichment/tracks/{track}/artist-image-information', [OnlineEnrichmentController::class, 'artistImageInformation']);
Route::get('/enrichment/tracks/{track}/lyrics', [OnlineEnrichmentController::class, 'lyrics']);
Route::get('/dashboard-metrics', DashboardMetricsController::class);
Route::get('/folders', FolderBrowserController::class);
Route::get('/favorites', [FavoritesController::class, 'ids']);
Route::get('/favorites/tracks', [FavoritesController::class, 'tracks']);
Route::post('/favorites/tracks/{track}', [FavoritesController::class, 'addTrack']);
Route::delete('/favorites/tracks/{track}', [FavoritesController::class, 'removeTrack']);
Route::get('/favorites/albums', [FavoritesController::class, 'albums']);
Route::post('/favorites/albums/{album}', [FavoritesController::class, 'addAlbum']);
Route::delete('/favorites/albums/{album}', [FavoritesController::class, 'removeAlbum']);
Route::get('/playlist-folders', [PlaylistsController::class, 'folders']);
Route::post('/playlist-folders', [PlaylistsController::class, 'createFolder']);
Route::patch('/playlist-folders/{folder}', [PlaylistsController::class, 'updateFolder']);
Route::delete('/playlist-folders/{folder}', [PlaylistsController::class, 'deleteFolder']);
Route::get('/playlists', [PlaylistsController::class, 'playlists']);
Route::post('/playlists', [PlaylistsController::class, 'createPlaylist']);
Route::get('/playlists/{playlist}', [PlaylistsController::class, 'playlist']);
Route::patch('/playlists/{playlist}', [PlaylistsController::class, 'updatePlaylist']);
Route::delete('/playlists/{playlist}', [PlaylistsController::class, 'deletePlaylist']);
Route::post('/playlists/{playlist}/tracks', [PlaylistsController::class, 'addTracks']);
Route::post('/playlists/{playlist}/tracks/{track}', [PlaylistsController::class, 'addTrack']);
Route::delete('/playlists/{playlist}/items', [PlaylistsController::class, 'removeItems']);
Route::delete('/playlists/{playlist}/items/{item}', [PlaylistsController::class, 'removeItem']);
Route::patch('/playlists/{playlist}/items/reorder', [PlaylistsController::class, 'reorderItems']);
